#!/usr/bin/env bash

set -u
set -o pipefail

readonly all_files=$( find tests/unit -maxdepth 1 -type f -name '*.js' )

for f in ${1:-$all_files}
do
  output=$(node --harmony-top-level-await --experimental-modules --es-module-specifier-resolution=node "$f")
  status="$?"
  if [[ "$status" -eq 0 ]]
  then
    printf '%s' "${output}"
  else
    printf '%s\n' "${output}"
    exit "$status"
  fi
done
