#!/usr/bin/env bash

set -u
set -o pipefail

readonly all_files=$( find tests/unit -maxdepth 1 -type f -name '*.js' )

if [[ -z "$all_files" ]]
then
  printf '%s\n' "No test files found in tests/unit" >&2
  exit 1
fi

for f in ${1:-$all_files}
do
  output=$(node "$f")
  status="$?"
  if [[ "$status" -eq 0 ]]
  then
    printf '%s' "${output}"
  else
    printf '%s\n' "${output}"
    exit "$status"
  fi
done
