#!/usr/bin/env bash

set -u
set -o pipefail

for f in tests/unit/*.js;
do
  output=$(node --harmony-top-level-await --experimental-modules --es-module-specifier-resolution=node "$f");
  status="$?"
  if [[ "$status" -eq 0 ]];
  then
    printf '%s' "${output}";
  else
    printf '%s\n' "${output}";
    exit "$status"
  fi
done;
