name: Tests
on: [ push ]
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Caddy
        run: .github/scripts/install-caddy
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Run tests
        run: |
          yarn
          yarn build:data
          yarn start:server
          yarn test
          yarn stop:server
